services:
  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-control.rule=Host(`control`)"
    networks:
      - default
      - frontend

networks:
  frontend:
    external: true
